services:
  postgres:
    image: postgres:17-alpine
    container_name: autoparts_postgres
    environment:
      POSTGRES_DB: autoparts_db
      POSTGRES_USER: autoparts_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
