spring.application.name=AutoPartsRequestProcessingSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/autoparts_db
spring.datasource.username=autoparts_user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
